#!/bin/bash

picom
feh --bg-scale "$HOME/.wallpapers/.excluded/none.jpg"
setxkbmap -layout gb,se,pt -option 'grp:alt_shift_toggle'

mouse_name="Logitech G502 HERO Gaming Mouse"
mouse_id="$(xinput | grep "$mouse_name  " | awk '{print $8}' | cut -c 4-5)"

xinput set-prop "$mouse_id" "libinput Accel Profile Enabled" 0, 1
xinput set-prop "$mouse_id" "libinput Accel Speed" -0.6
